name: ✨ 기능 추가 / 수정
description: 새로운 기능을 추가했거나 기존 기능을 수정했을 때 사용
title: "[Feature] "
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        ## MR 개요
        이 MR에서 변경된 내용을 간단히 요약해주세요.
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: 주요 변경 사항
      description: 어떤 코드가 어떻게 바뀌었는지 요약해주세요.
      placeholder: |
        - Feat: xxx 추가
        - Refactor: yyy 구조변경
        - Fix: zzz 문제 해결결
    validations:
      required: true
  - type: checkboxes
    id: test
    attributes:
      label: 테스트항목
      options: 
        - label: 게임플레이 테스트 완료
        - label: 빌드 테스트 완료
  - type: textarea
    id: screenshot
    attributes: 
      label: 스크린샷(선택)
      description: 변경된 UI나 기능을 스크린샷으로 첨부해주세요.
      placeholder: 변경된 화면 또는 동작 영상
  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      options:
        - label: 코드 스타일 가이드 준수
        - label: 불필요한 디버그 로그 제거
        - label: 성능 최적화 고려
        - label: 예외 처리 구현
        - label: 주석 작성성