name: ✨ 기능 추가 제안
description: 새로운 기능을 추가
title: "[Feature] "
labels: [feature]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: 기능 설명
      placeholder: 추가하고자 하는 기능에 대해 설명해주세요
    validations:
      required: true
  - type: textarea
    id: feature_details
    attributes:
      label: 구현 방법
      placeholder: 구현 방법에 대해 간략하게 작성해주세요
  - type: checkboxes
    id: components
    attributes:
      label: 필요한 구성 요소
      options:
        - label: Unity 컴포넌트
        - label: 스크립트
        - label: 애셋/리소스
        - label: UI/UX
        - label: 사운드
  - type: textarea
    id: useful_links
    attributes:
      label: 참고자료
      placeholder: 레퍼런스나 예시 이미지/영상이 있다면 첨부해주세요요